// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-toast": {
      name: "use-toast",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-toast.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-toast.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
